// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  docs: [
    "index",
    {
      type: "category",
      label: "Getting Started",
      // 默认打开
      collapsed: false,
      items: ["guides/user-guide"],
    },
    {
      type: "category",
      label: "Architecture Design",
      collapsed: false,
      items: ["design/design", "design/architecture"],
    },
    {
      type: "category",
      label: "AI Assist",
      collapsed: false,
      items: [
        {
          type: "autogenerated",
          dirName: "ai",
        },
      ],
    },
  ],
};

module.exports = sidebars;
